### PR TITLE
Major code cleanup. UNTESTED

### PR DESCRIPTION
**Pull request by pykong**
- Formatted according to PEP8 and yapf.
- Removed anti-patterns such as returning None.
- Refactored methods to eliminate code reuse.
- Broke up long expressions into smaller bits to enhance comprehensibility.
- Sorted imports via isort.

_(@wvlia5 I was under the impression I already opened a PR with the same content yesterday. 
Albeit I was not able to find it today. And I did not receive any notification. Therefore I assume I made an error when opening that PR. In case anything is odd in this regard just let me know.)_

### CODE REVIEW

**Comment by matiasmorant** [comment]
Thanks, i'll be checking this out.

**Comment by pykong** [comment]
As with all software regular clean ups _(preferably by some one else than the original author),_ prevent too much technical debt creeping in. Great, you are positive about this PR, because such a cleanup will make the code maintainable and more accessible to other authors joining in.

Regarding empty string versus None as return values: Both evaluate to falsely, meaning they should behave in the same way. This is unless you explicitly check for an empty string, which as far as I checked your program does not do.

I have written [a short example on codepen](http://www.codeskulptor.org/#user43_Qtlkg2Wp4u_1.py) to illustrate this behavior.

Regarding swapping sleep with async: See [this example](https://repl.it/KM1b).
Do not be intimidated due to the many lines of code. Actually just lines 21 and 32 are important to understand the non-locking nature of this example. Your current code is almost there already, needing to add only "async" and changing "sleep" to "async.sleep".

You can use the PR as a starting point and correct the (hopefully) few things I may have broken. 

Just ask here, if you got any questions.

**Comment by pykong** [comment]
Closed by accident. Reopened.

**Comment by matiasmorant** [comment]
About None vs. Empty string: that is true if i used it only for checking the truth value, but maybe it's used for something else (i.e. concatenating with another string), in which case it wouldn't work. But I don't remember if that's the case. 
I'll be checking that asinc example, thanks

**Comment by pykong** [comment]
The empty string was used on two occasions, as a string argument to the fill_view command.
I do not know how Sublime handles None type arguments.

**Comment by pykong** [comment]
I tested and indeed returning an empty string is necessary.
Hence I rolled back that method.

**Comment by matiasmorant** [comment]
I thought it would be easier to correct pep8 myself... Sorry for that, I appreciate the work you did. Anyways, the changes you proposed are mostly in place now I think. Thanks

**Comment by matiasmorant** [comment]
I wrote some issues which might give you some useful ideas in case you wanted to contribute something else. Fresh ideas are most welcome

**Comment by pykong** [comment]
That is totally fine. I see you cleaned up your code pretty well, not only PEP8 but also some nice code refactoring. It will encourage others to contribute. Also, great this plugin is on PackageControl now (and already trending).
I hope you know how important your work is to all who code Python on Sublime Text!

**Pull request closed without merging**
